# Configuration for the BIOfid Literature Harvester
# Created by Adrian Pachzelt & Giuseppe Abrami
# https://www.biofid.de/en


General:
   # The directory to write all the output
   output-path: /harvesting
   
   # Whether to overwrite existing files (true) or not (false)
   overwrite: false
   
   # Delay between requests to an API in milliseconds; Default: 0
   request-delay: 100


ItemFilter:
  # The ItemFilter section is completely optional.
  # It allows setting filter criteria for all Harvesters (in the section "General") or for a specific harvester
  # (referring its name as given in the "Harvester" section below). If both is given, a "General" filter and a specific
  # filter for a harvester, only (!) the filters of the specified harvester apply!

  # Checks an Item object's citation for filter criteria
  General:
    # A filter criteria can be applied to ALL Harvesters, putting it in the "General" section.
    Year:
      # Filter for publication year. The parameter name (in this case "Year") is the parameter in the item that will
      # be evaluated. The name is case-insensitive.
      EqualLess:
        # Allowed (case-insensitive) keywords for integer comparisons are
        # "LessThan", "EqualLess", "Equal", "EqualGreater", "Greater".
        # The parameter type is deduced automatically.
        1923
      strict:
        # The default behaviour of filters is to pass an item, if it does not provide the requested parameter (in this
        # case "Year").
        # The "strict" parameter is disabled ("false") per default and is optional. If set "true", the requested
        # parameter has to be given in each item. If an item cannot provide the requested parameter, it will be
        # filtered out.
        true
  BHL:
    # A filter for a specific Harvester can be stated by using the Harvester's name.
    # More general filters (i.e. from the "General" section) will all(!) be overwritten.
    Title:
      contains:
        # For string comparisons "Equal" or "Contains" can be given as comparison keywords.
        "test"


# Configure additional Harvesters below after implementing them.
# Every Harvester needs to have a unique name. Also, it needs to provide a "class", so
# the package and the name of the respective Harvester implementation. Everything else
# that is contained in the configuration is up to the respective implementation and
# will be handed to the respective Harvester.
Harvesters:
- BHL:
    class: de.biofid.services.crawler.BhlHarvester
     
    # Providing the keyword "api-key" will cause the crawler to provide the respective
    # Harvester to use this key. You may choose to provide a file were the key is stored
    # as the only value or provide the key directly here instead.
    api-key: config/bhl-api-key.txt

    # Overwrites the general overwriting rule for this harvester
    overwrite: false

    # If only to download the metadata and not the text files
    metadata-only: false

    # Instead of a list you can provide a file that contains the items/titles in a list with one
    # item/title per line.

    # Single issues of e.g. a journal series.
    items:
      - 1234
      - 5678

    # Titles are collections of items. E.g. a journal series.
    # So, when provided with title IDs, all its items will be downloaded.
    # This can be given as a file.
    titles: path/to/some/file.txt
     
        
- Zobodat:
    # This crawler is set up to download all texts from Zobodat, when no items are given.
    class: de.biofid.services.crawler.zobodat.ZobodatHarvester
    metadata-only: true

    # If this is true, all items in Zobodat will be crawled and the metadata is downloaded.
    # If given with an item or title list, the text files of the given items will be downloaded.
    crawl-all-items: true
